---
- name: "push your private key"
  tags: [ssh]
  hosts: all
  strategy: free
  gather_facts: true
  tasks:
    - name: Set authorized key taken from file
      authorized_key:
        user: user
        state: present
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
- name: "Configure the user for sudo no password"
  tags: [sudo]
  hosts: all
  strategy: free
  gather_facts: true
  tasks:
    - name: "Ensure dependencies are installed"
      package:
        name:
          - sudo
        state: present
    - name: "Make sure we have a wheel group"
      group:
        name: wheel
        state: present
    - name: "Allow wheel group to have passwordless sudo"
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'
    - name: "Make sure we have a user group"
      group:
        name: user
        state: present
- name: "Install docker engine and docker compose"
  tags: [docker]
  hosts: all
  strategy: free
  gather_facts: true
  roles:
    - role: install-docker-engine
    - role: install-docker-compose
